server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    resolver 8.8.8.8 valid=30s;
    set $backend "https://bigdata-backend-770757350817.us-central1.run.app";

    location /chat {
        proxy_pass $backend;
        proxy_set_header Host bigdata-backend-770757350817.us-central1.run.app;
        proxy_ssl_server_name on;
    }

    location /analyze-log {
        proxy_pass $backend;
        proxy_set_header Host bigdata-backend-770757350817.us-central1.run.app;
        proxy_ssl_server_name on;
    }

    location /analyze-airflow-task {
        proxy_pass $backend;
        proxy_set_header Host bigdata-backend-770757350817.us-central1.run.app;
        proxy_ssl_server_name on;
    }

    location /analyze-k8s-pod {
        proxy_pass $backend;
        proxy_set_header Host bigdata-backend-770757350817.us-central1.run.app;
        proxy_ssl_server_name on;
    }

    location /index/ {
        proxy_pass $backend;
        proxy_set_header Host bigdata-backend-770757350817.us-central1.run.app;
        proxy_ssl_server_name on;
    }

    location /lineage/ {
        proxy_pass $backend;
        proxy_set_header Host bigdata-backend-770757350817.us-central1.run.app;
        proxy_ssl_server_name on;
    }

    location /ops/ {
        proxy_pass $backend;
        proxy_set_header Host bigdata-backend-770757350817.us-central1.run.app;
        proxy_ssl_server_name on;
    }

    location /health {
        proxy_pass $backend;
        proxy_set_header Host bigdata-backend-770757350817.us-central1.run.app;
        proxy_ssl_server_name on;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
